### ISSUE TITLE
Auto refresh does not reload list

### ISSUE THREAD

**Issue by pwnell** [brentsimmons/NetNewsWire#530] opened 2019-01-31 20:38 UTC
Auto refresh seems to be loading new feeds correctly, however, even with manual feed refresh, the actual list never gets updated (All Unread) unless I click off the All Unread feed, and then back on it.  Therefore, the All Unread feed does not auto update its contents, just the item count.

**Comment by brentsimmons** [comment] 2019-01-31 21:10
Good catch! Quite right. This hasn’t been done yet.

(Closed because it’s a duplicate of #338.)

**Closed by brentsimmons** 2019-01-31 21:10 UTC
