### ISSUE TITLE
Smartlists

### ISSUE THREAD

**Issue by streebgreebling** [brentsimmons/NetNewsWire#981] opened 2019-09-05 18:45 UTC
Way back, NNW used to support SmartLists. I found these so useful, indeed, when they stopped I moved away to other, inferior, RSS tools. So please could they be reintroduced?

**Comment by brentsimmons** [comment] 2019-09-05 20:11
Yup!

Duplicate of https://github.com/brentsimmons/NetNewsWire/issues/217

**Closed by brentsimmons** 2019-09-05 20:11 UTC
