### ISSUE TITLE
Feature Request: restore selection in sidebar when app is restarted

### ISSUE THREAD

**Issue by schriftgestalt** [brentsimmons/NetNewsWire#900] opened 2019-08-28 06:45 UTC

**Comment by ned21** [comment] 2019-09-07 09:56
+1 to this: I keep all my feeds in folders. Whenever I start NNW, all folders are collapsed and I have to go through and expand my favourites before I start reading. Retaining the open/closed state of folders in the sidebar across restarts would be a big time-saver for me.

**Comment by brentsimmons** [comment] 2019-09-07 21:01
Duplicate of #300.

**Closed by brentsimmons** 2019-09-07 21:01 UTC
