### ISSUE TITLE
Feedbin and Micro.blog feeds: ideally we’d have the user avatar instead of the feed avatar

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#669] opened 2019-05-20 21:25 UTC
Same behavior as with the OnMyMac account. I’m not sure if FeedBin data makes this data available, though.

**Comment by vincode-io** [comment] 2019-05-20 23:11
Unfortunately the only author information we get is the Author Name for articles.
https://github.com/feedbin/feedbin-api/blob/master/content/entries.md

The icons.json service returns us some icons, but those are by domain, not author.
https://github.com/feedbin/feedbin-api/blob/master/content/icons.md

**Comment by brentsimmons** [comment] 2019-05-22 05:41
Do we have enough data from the FeedBin version of this feed to be able to override and grab avatars via the built-in mechanism?

**Comment by manton** [comment] 2019-05-22 12:28
Let me know if I can help with this. If Feedbin sync gives easy access to the original JSON Feed URL, we could download that on first sync (or occasionally later) and parse it for the Micro.blog avatars.

**Comment by vincode-io** [comment] 2019-05-23 13:56
@benubois  Do you see anyway that we can get the author avatar URL instead of just the favicon URL for the domain? Have I missed something?

**Comment by benubois** [comment] 2019-05-24 00:20
Hi @vincode-io,

Feedbin has been capturing this data, but until now it hasn't been available in the API. I went ahead and added to option to get it.

For entries, you can use the existing `?mode=extended` parameter. There's a new `json_feed` key that includes the extra JSON Feed metadata.

Request:

```bash
$ curl --silent --user "ben+jsonfeed@benubois.com:2fj3oij2fjawfjj" "https://api.feedbin.com/v2/entries.json?mode=extended"
```

Response:

```json
[
   {
      "id" : 2107460827,
      "json_feed" : {
         "id": "3705386",
         "author" : {
            "avatar": "https://www.gravatar.com/avatar/68d93be700edec53fdcf153335d87ef5?s=96&d=https%3A%2F%2Fmicro.blog%2Fimages%2Fblank_avatar.png",
            "_microblog" : {
               "username": "leo"
            },
            "name": "Leo Laporte",
            "url": "https://leolaporte.com"
         }
      },
      "author": "Leo Laporte",
      "images" : null,
      "created_at": "2019-05-24T00:09:38.417757Z",
      "published": "2019-05-23T23:19:03.000000Z",
      "extracted_articles" : [],
      "url": "https://www.nytimes.com/2019/05/23/us/politics/assange-indictment.html",
      "original" : null,
      "enclosure" : null,
      "twitter_id" : null,
      "twitter_thread_ids" : [],
      "summary": "Assange Indicted Under Espionage Act, Raising First Amendment Issues - The New York Times nytimes.com",
      "content": "Assange Indicted Under Espionage Act, Raising First Amendment Issues - The New York Times <a href=\"https://www.nytimes.com/2019/05/23/us/politics/assange-indictment.html\">nytimes.com</a>",
      "title" : null,
      "feed_id" : 1437276
   }
]
```

For subscriptions, you can also use the `?mode=extended` parameter.

Request:

```bash
$ curl --silent --user "ben+jsonfeed@benubois.com:2fj3oij2fjawfjj" "https://api.feedbin.com/v2/subscriptions.json?mode=extended"
```

Response:

```json
[
  {
    "id" : 4876950,
    "json_feed" : {
      "version": "https://jsonfeed.org/version/1",
      "feed_url": "https://micro.blog/feeds/manton.json",
      "icon": "https://micro.blog/images/icons/favicon_256.png",
      "title": "Micro.blog - manton timeline",
      "favicon": "https://micro.blog/images/icons/favicon_32.png",
      "home_page_url": "https://micro.blog/"
    },
    "feed_id" : 1437276,
    "title": "Micro.blog",
    "created_at": "2019-05-24T00:10:03.298692Z",
    "feed_url": "https://micro.blog/feeds/manton.json",
    "site_url": "https://micro.blog/"
  }
]
```

Does that get you everything you need?

**Comment by vincode-io** [comment] 2019-05-24 00:27
@benubois That is awesome!  I think we are good now. I’ll try to get to adding it this weekend.

**Comment by vincode-io** [comment] 2019-05-26 23:16
@benubois I'm running into some things.  One is that it doesn't look like mode=extended is propagated to the paging information in the Links: response header like the other query parameters are.  Is that expected behavior?  

The other is that I'm not getting all the json_feed information that I expect.

```curl -i --request GET --user "mo@vincode.io:XXXXXXX" "https://api.feedbin.com/v2/feeds/1296383/entries.json?since=2019-02-27T00:01:07.112000Z&per_page=1&mode=extended```

```
[
    {
        "id": 2109485206,
        "feed_id": 1296383,
        "title": "NetNewsWire Meetup at WWDC",
        "author": "Brent Simmons",
        "summary": "Find me at the Fairmont hotel lobby bar at 4 pm on Monday (June 3). I don’t expect a large group — not like the Micro.blog meetup or Automators meetup. So I think we can keep it simple and just meet there in the hotel. (It’s a pretty big lobby.)",
        "content": "\u003cp\u003eFind me at the Fairmont hotel lobby bar at 4 pm on Monday (June 3).\u003c/p\u003e\n\n\u003cp\u003eI don’t expect a large group — not like the Micro.blog meetup or Automators meetup. So I think we can keep it simple and just meet there in the hotel. (It’s a pretty big lobby.)\u003c/p\u003e\n",
        "url": "https://inessential.com/2019/05/26/netnewswire_meetup_at_wwdc",
        "published": "2019-05-26T18:41:55.000000Z",
        "created_at": "2019-05-26T18:48:50.581283Z",
        "original": null,
        "twitter_id": null,
        "twitter_thread_ids": [],
        "images": null,
        "enclosure": null,
        "extracted_articles": [],
        "json_feed": {
            "id": "https://inessential.com/2019/05/26/netnewswire_meetup_at_wwdc"
        }
    }
]
```

**Comment by benubois** [comment] 2019-05-30 21:40
@vincode-io,

> One is that it doesn't look like mode=extended is propagated to the paging information in the Links: response header like the other query parameters are. 

My mistake. This should be fixed now. Thanks!

> The other is that I'm not getting all the json_feed information that I expect.

What is missing that you would expect to find for this entry? Looking at the [source](https://inessential.com/feed.json) of that JSON Feed, I'm not seeing anything missing. If you're looking for the avatar, with a JSON Feed it can either be specified at the feed level or at the item level. In this case it's available only at the feed level so it would show up under the subscriptions endpoint:

```
https://api.feedbin.com/v2/subscriptions.json?mode=extended
```

**Comment by vincode-io** [comment] 2019-05-30 23:26
@benubois Many thanks for looking at this.  I imagine you've got to be crazy busy running Feedbin.

I should have looked at the json source myself.  I was thinking that the avatar url you see on the feed itself would be on the entries, but it isn't.

@brentsimmons Right now it looks like we will get the author avatar if it is specified on the feed article, but not if it is specified just for the feed itself.

**Comment by brentsimmons** [comment] 2019-05-30 23:31
My main use is for the feed of my timeline: https://micro.blog/feeds/brentsimmons.json

Which I think has per-article avatars, so it should be good.

**Comment by vincode-io** [comment] 2019-05-31 12:38
Let's close this one out then.

**Closed by vincode-io** 2019-05-31 12:38 UTC
