### ISSUE TITLE
iOS: Unread count should be shown while browsing articles

### ISSUE THREAD

**Issue by blackketter** [brentsimmons/NetNewsWire#1521] opened 2020-01-02 21:35 UTC
I see that the unread count for a list is visible in the list view, next to the title of the list, but that information is missing when browsing articles.  It would be great to show the unread count next to the list name at the top of the article view as a progress indicator while reading a list.

Something like this in the top left of the screen, for example: 

< All Unread (25)

**Comment by vincode-io** [comment] 2020-01-02 22:25
This is a good idea and one that I’ve contemplated myself. The problem is with longer named timelines.  If the name is too long then the back button isn’t named.  It is just “Back”. This is controlled by the operating system. Since we can’t consistently put the unread count in the back button, we haven’t done it. 

I’m going to close this issue, but feel free to comment on it. If anyone has a design that works for this, we would like to discuss it.

**Closed by vincode-io** 2020-01-02 22:25 UTC

**Comment by blackketter** [comment] 2020-01-02 23:34
I'm guessing that it's not possible to get the dimensions of the "< Back" button and then place the unread count indicator a little to the right of it.  If it is possible, this might be worth exploring.

A totally different approach would be to incorporate the unread count in the "next unread" button at the bottom. Tap it and see the next unread and watch the count go down!

Just brainstorming here...

**Comment by blackketter** [comment] 2020-01-09 22:21
This issue is most important for reading in the context of the All Unread smart feed.  Even if there isn't a general solution for every context, it would be great to have it in just this feed!

Now that I'm really efficient in blasting through my unread articles via the swipe gesture, I find myself having to pop out and then back in to see how many remain.  Breaks my flow, man!
