### ISSUE TITLE
drag and drop feeds into folders

### ISSUE THREAD

**Issue by hobbsy** [brentsimmons/NetNewsWire#363] opened 2018-04-13 04:01 UTC
Is it possible to drag a feed in the sidebar into a folder?

If I initially choose a folder when adding a new feed, I am unable to move it into a different one

If I right-click on a feed in the sidebar, maybe an option to "edit feed" (change address, change folder)

Thanks for creating this Brent

**Comment by hopkapi** [comment] 2018-07-26 20:53
I'm super confused, is there no way to actually add feeds to a folder? I'm partly confused because I seem to have some in a folder but I don't know how I managed to add them in a prior build.

**Comment by brentsimmons** [comment] 2018-07-26 20:55
This feature hasn’t been done yet. It will be, for 1.0.

When adding a feed, you can choose a folder — there’s a popup menu in the add-feed sheet. But that’s the only way, currently.

**Comment by hopkapi** [comment] 2018-07-26 20:56
Hmm, does it inherent them from OPML somehow?

**Comment by brentsimmons** [comment] 2018-07-26 20:57
Yes — it also picks up folders from OPML.

**Comment by brentsimmons** [comment] 2018-09-05 04:36
Duplicate of #13.

**Closed by brentsimmons** 2018-09-05 04:36 UTC
