### ISSUE TITLE
Evergreen fails to refresh automatically

### ISSUE THREAD

**Issue by betalogue** [brentsimmons/NetNewsWire#378] opened 2018-07-28 14:25 UTC
Even though Preferences is set to refresh feeds every hour, nothing happens automatically. Only manual refresh works.

2014 Mac Pro with macOS 10.13.6

Evergreen 1.0d42 (1090)

**Comment by brentsimmons** [comment] 2018-07-28 21:45
Good catch. That feature hasn’t been written yet.

**Comment by owensd** [comment] 2018-08-16 19:54
Hah, I was wondering why this wasn't working! Good to know it simply is NYI.

**Comment by brentsimmons** [comment] 2018-09-05 04:35
Duplicate of #60.

**Closed by brentsimmons** 2018-09-05 04:35 UTC
