### ISSUE TITLE
Feature Request: OPML Syncing

### ISSUE THREAD

**Issue by voldyman** [brentsimmons/NetNewsWire#918] opened 2019-08-30 23:47 UTC
Today NetNewWire supports feedbin and will probably support feedly in the future.

What if the users could synchronize their hosted version OPML file between difference machines/NetNewsWire instances.

A user would upload their OPML file to github or Dropbox and add it to NNW, whenever they want to subscribe to a new feed they update their OPML file (by hand or by adding a feed to the app and exporting it to OPML) and all the instances of NNW will fetch the new OPML file and add the new feed.

This removes dependence on third party services and allows users to synchronize feeds between multiple instances of the application.

**Comment by brentsimmons** [comment] 2019-08-30 23:48
In that scenario, would you not be interested in syncing read/unread/starred status of articles?

**Comment by voldyman** [comment] 2019-08-31 02:00
Yes, that would be ideal but difficult to do without a service.

**Comment by akirk** [comment] 2019-09-01 14:15
I suppose this depends on the use case but for people (like me) who use RSS more in a "twitter stream" way, OPML syncing would be very practical.

For example, when you manage your subscriptions of (partially private feeds) with something like the [Friends plugin for WordPress](https://wordpress.org/plugins/friends/) but would like to consume the RSS articles with NNW, you could subscribe NNW to the OPML file (see screenshot 4 on the plugin page).

**Comment by brentsimmons** [comment] 2019-09-01 18:45
Duplicate of #626

**Closed by brentsimmons** 2019-09-01 18:45 UTC
