### ISSUE TITLE
Timeline grouped by feed and sorted chronologically 

### ISSUE THREAD

**Issue by JonathanMonahan** [brentsimmons/NetNewsWire#360] opened 2018-03-19 13:42 UTC
An enhancement suggestion:

If I have articles sorted by oldest article on top, then I can read articles in chronological order grouped by feed by finding the first unread article and then using Space to page through them.

There are a couple of disadvantages:
- I have to find the first feed with an unread article and click on it, then scroll down (through quite a long list) to find and click on the first unread article.
- If I press Space once too often on an article, the next article is shown, which might be in another feed, so I cannot easily go back to the end of the last article which I've not finished reading.  I may not even have registered which feed it was in, in which case I can't find it at all!

A keystroke to go back (undo Space) would be useful I'm sure, but I also think a Smart Feed that is grouped by feed and sorted chronologically would be even better.  I would be able to see the articles I've already read in this session in this feed (and go back to them), and I would be able to read a stream of consciousness from one feed in order.

The Unread Smart Feed is fine for those who read chronologically, but I tend to spend an hour or so every few days, across over a hundred feeds in a wide variety of subjects, so the Unread Smart Feed gives me a very chopped up experience.

A further extension could perhaps allow categorisation of the feeds, so that the Smart Feed could show articles grouped by category, then grouped by feed, and sorted chronologically.

BTW, you are doing a great job - Evergreen has quickly become everything I've wanted from a feed reader (apart from the above).  Thank you.

**Comment by willie** [comment] 2018-10-11 14:46
This is somewhat related to https://github.com/brentsimmons/NetNewsWire/issues/356

**Comment by vincode-io** [comment] 2019-09-13 16:12
This is a duplicate of #422 and has been implemented in pull request #1016.

**Closed by vincode-io** 2019-09-13 16:12 UTC
