### ISSUE TITLE
Feature Request: Only show feeds with unread articles

### ISSUE THREAD

**Issue by bviefhues** [brentsimmons/NetNewsWire#950] opened 2019-09-03 13:32 UTC
Would be great if NNW had an option to only show feeds with unread articles in the sidebar. Feedbin can do this in its web UI. Note: this is not NNW's "Unread" article list. It rather filters the Folder/Feed tree, i.e. preserves the structure.

**Comment by brentsimmons** [comment] 2019-09-03 20:14
I hear you.

Duplicate of https://github.com/brentsimmons/NetNewsWire/issues/129

**Closed by brentsimmons** 2019-09-03 20:14 UTC
