### ISSUE TITLE
[Feature Request] Syncing over iCloud (or something else which is not paid)

### ISSUE THREAD

**Issue by fraander** [brentsimmons/NetNewsWire#1297] opened 2019-11-15 00:03 UTC
I want to be able to sync what I have read and what I have not between two computers, as of right now I cannot do this unless I pay for Feedbin (which I do not want to pay for).

**Comment by vincode-io** [comment] 2019-11-15 00:05
This is a duplicate of #491.

**Comment by brentsimmons** [comment] 2019-11-15 00:06
We hear you! It‘s a good idea. We have a bunch of other things to do before we can consider this, but we will consider it.

**Closed by vincode-io** 2019-11-15 00:05 UTC
