### ISSUE TITLE
Feature Request: Hide Read Items OR Sort by Read/Unread

### ISSUE THREAD

**Issue by sccardais** [brentsimmons/NetNewsWire#972] opened 2019-09-05 09:41 UTC
I would like the ability to hide articles that I've marked as READ.

**Comment by brentsimmons** [comment] 2019-09-05 20:17
We hear you!

Duplicate of https://github.com/brentsimmons/NetNewsWire/issues/130

**Closed by brentsimmons** 2019-09-05 20:17 UTC
