### ISSUE TITLE
iOS: Share sheet closes after tapping an app icon

### ISSUE THREAD

**Issue by nathansnelgrove** [brentsimmons/NetNewsWire#1484] opened 2019-12-29 17:33 UTC
When I tap the share icon on an article, and then tap on, say, Tweetbot, I’ll get the tweet preview pane. When I tap the preview pane to edit it, the whole share sheet closes — as if it were never opened.

**Comment by vincode-io** [comment] 2019-12-29 18:21
Is this problem only happening for you when using Tweetbot?  I just tested the share sheet with Mail and Messages and it is working as intended.

**Comment by nathansnelgrove** [comment] 2019-12-29 18:49
Good question! It seems to happen only with Tweetbot, and only when I’ve tapped to read a web article in the app. So it only happens in the web view. Sorry; I didn’t realize that in my initial report.

**Comment by vincode-io** [comment] 2019-12-29 18:53
It looks like this is a bug in the Tweetbot share extension.  I’m closing this issue since there isn’t anything we can do to resolve it.

**Closed by vincode-io** 2019-12-29 18:53 UTC
