### ISSUE TITLE
In App YouTube support

### ISSUE THREAD

**Issue by venkatasg** [brentsimmons/NetNewsWire#454] opened 2018-09-10 21:03 UTC
I noticed today that YouTube video embeds(not sure of the technical term for this. Maybe its just a YouTube link) do not show up in the reader. Attached are two screenshots - one from latest version of NetNewsWire and the other from Reeder app.

![screen shot 2018-09-10 at 17 02 32](https://user-images.githubusercontent.com/22871413/45324204-72d36080-b51b-11e8-82f5-7c8138809642.png)
![screen shot 2018-09-10 at 17 02 44](https://user-images.githubusercontent.com/22871413/45324205-72d36080-b51b-11e8-9354-6a777faf65ba.png)

**Comment by brentsimmons** [comment] 2018-09-11 18:16
What’s the URL of the feed?

**Comment by venkatasg** [comment] 2018-09-11 19:02
http://feeds2.feedburner.com/forkbombr/rss2

**Comment by danielpunkass** [comment] 2019-02-15 19:03
I was not able to reproduce this specifically with 512 pixels because the pertinent video post is too old now to show up in the feed. But I was able to find another video embed that seemed to work fine, from macstories.net feed, the article "Apple Shares Apple Music Ads". 
<img width="783" alt="image" src="https://user-images.githubusercontent.com/14606/52878371-71d9d700-312a-11e9-8708-4c8b1c5583f4.png">

**Comment by danielpunkass** [comment] 2019-02-15 19:03
I recommend closing this as fixed unless another example of a non-working YouTube embed comes up.

**Closed** 2019-02-15 19:05 UTC
