### ISSUE TITLE
Support for custom style sheets

### ISSUE THREAD

**Issue by nicksherman** [brentsimmons/NetNewsWire#597] opened 2019-04-10 22:37 UTC
Probably my favorite feature of NetNewsWire 3 was the ability to use my own customized style sheets. Bringing that functionality back to the new version would be my dream – especially if it supported some of the CSS options that weren't supported previously (e.g. media queries, if I remember correctly).

**Comment by brentsimmons** [comment] 2019-04-10 23:05
It’s definitely on to the to-do list! It won’t make it into 5.0, but it will get done in a later release, for sure.

**Comment by brentsimmons** [comment] 2019-06-08 01:24
Duplicate of #19.

**Closed by brentsimmons** 2019-06-08 01:24 UTC
