### ISSUE TITLE
Change the dock Icon PLS

### ISSUE THREAD

**Issue by dkotanid** [brentsimmons/NetNewsWire#482] opened 2018-09-25 06:18 UTC
App working great so far! 10.14 Macos Mojave, but the icon is ugly...please change it! More futuristic more minimal...something else///

**Comment by tylerneu** [comment] 2018-11-09 15:03
https://github.com/brentsimmons/NetNewsWire/issues/439

**Comment by brentsimmons** [comment] 2018-11-22 05:51
Duplicate of #439.

**Closed by brentsimmons** 2018-11-22 05:51 UTC
