### ISSUE TITLE
iOS: Missing images on feed

### ISSUE THREAD

**Issue by kenrachynski** [brentsimmons/NetNewsWire#1294] opened 2019-11-14 02:00 UTC
I’m not entirely sure what is happening here. I’m subscribed to kottke’s feed and the images in the articles aren’t showing up. I normally see something like this:
![IMG_0010](https://user-images.githubusercontent.com/867597/68820072-667af400-0647-11ea-9ac1-4a4f88dd541e.png)

This time, however, I briefly saw this before getting the black box.
![IMG_0011](https://user-images.githubusercontent.com/867597/68820100-7db9e180-0647-11ea-88c1-965dd9481b90.png)

This is with a local account on my iPad and this is the only feed I’m seeing this behaviour on. http://feeds.kottke.org/json is the feed url in case I’ve changed it.

**Comment by vincode-io** [comment] 2019-11-14 02:05
This is a duplicate of #1280 and is resolved.  You'll see the fix in the next TestFlight build.

**Closed by vincode-io** 2019-11-14 02:05 UTC

**Comment by kenrachynski** [comment] 2019-11-14 02:06
Oh, I can tap on the image and have it show up on screen. (second image there) When I close the image, I do briefly see the image in that black box before it goes black, again.
